rescue_path: "file:////home/cdsw/ons-spark/ons-spark/data/animal_rescue.parquet"
population_path: "file:////home/cdsw/ons-spark/ons-spark/data/population.parquet"
checkpoint_path: "file:////home/cdsw/ons-spark/checkpoints"
